### ISSUE TITLE
a-nav: display inline-block

### ISSUE THREAD

**Issue by kenle** [hoangthai1997/Homework_14#6]
https://github.com/hoangthai1997/Homework_14/blob/9ac5c37420e90fb84b0ee2fc5b5d0e9d68f1e8ef/1-atom.css#L8

`<a>` is inline by default and won't listen to padding.  You need to add display: inline-block.

Also please reset `<a>` style in reset.css.  Add something like:
```css
a {
   text-decoration: none;
   color: black:
   padding: 0;
   margin: 0;
}
```
